CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar(100) UNIQUE NOT NULL,
  "senha" varchar(100) NOT NULL,
  "cpf" varchar(15) UNIQUE NOT NULL,
  "cadastrado" timestamp NOT NULL DEFAULT (now()),
  "editado" timestamp DEFAULT null
);

CREATE TABLE "cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "cpf" varchar(15) UNIQUE NOT NULL,
  "telefone" varchar(15) DEFAULT null,
  "cadastrado" timestamp NOT NULL DEFAULT (now()),
  "editado" timestamp DEFAULT null
);

CREATE TABLE "venda" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "cliente_id" integer DEFAULT null,
  "forma_pagamento_id" integer NOT NULL,
  "total" decimal(10,2) NOT NULL,
  "cadastrado" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "forma_pagamento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "cadastrado" timestamp NOT NULL DEFAULT (now()),
  "editado" timestamp DEFAULT null
);

CREATE TABLE "categoria" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "cadastrado" timestamp NOT NULL DEFAULT (now()),
  "editado" timestamp DEFAULT null
);

CREATE TABLE "produto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "preco" decimal(10,2),
  "categoria_id" integer NOT NULL,
  "quantidade" integer NOT NULL,
  "unidade_medida" varchar NOT NULL,
  "cadastrado" timestamp NOT NULL DEFAULT (now()),
  "editado" timestamp DEFAULT null
);

CREATE TABLE "item" (
  "venda_id" integer,
  "produto_id" integer,
  "quantidade" integer NOT NULL,
  "desconto" decimal,
  "valor" decimal(10,2) NOT NULL,
  "cadastrado" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("venda_id", "produto_id")
);

ALTER TABLE "item" ADD FOREIGN KEY ("venda_id") REFERENCES "venda" ("id");

ALTER TABLE "item" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("id");

ALTER TABLE "venda" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id");

ALTER TABLE "venda" ADD FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id");

ALTER TABLE "produto" ADD FOREIGN KEY ("categoria_id") REFERENCES "categoria" ("id");

ALTER TABLE "venda" ADD FOREIGN KEY ("forma_pagamento_id") REFERENCES "forma_pagamento" ("id");