services:
  postgres:
    image: postgres:latest
    container_name: papelaria_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_tp
    volumes:
      - ../db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
      - db_tp_pgdata:/var/lib/postgresql/data

volumes:
  db_tp_pgdata:
