version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: papelaria_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: papelaria
    volumes:
      - ../db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
      - papelaria_pgdata:/var/lib/postgresql/data

volumes:
  papelaria_pgdata:
